name: gbrunner

channels:
  - conda-forge

dependencies:
  - python=3.13
  - pip
  #
  - basedpyright
  - devtools
  - jupyter
  - numpy
  - pandas
  - polars
  - pydantic
  - scikit-learn
  - scipy
  - tqdm
  #
  - pip:
      - anndata
      - arboreto
      - lightgbm
      - scanpy
      - xgboost
